Repository Hanagotchi/measurements, pull requests merged in 2024-06, with the labels that each got.

#28 HAN-112: servicio de autenticación
  Makefile
  app/controller/measurements.py
  app/exceptions/MeasurementsException.py
  app/external/Plants.py
  app/external/Users.py
  app/external/__init__.py
  app/main.py
  app/repository/measurements.py
  app/service/measurements.py
  app/service/rabbitmq/consumer.py
Labels: WIP

#29 Protocolo MQTT + Adaptación con Sensor Real + Control de Notificaciones
  .env.dist
  .github/workflows/linters.yml
  .gitignore
  README.md
  app/controller/measurements.py
  app/database/models/measurement.py
  app/external/Plants.py
  app/external/Users.py
  app/main.py
  app/main_rabbitmq.py
  app/models/measurement.py
  app/resources/message_parser.py
  app/resources/notification_checker.py
  app/resources/rule_parser.py
  app/schemas/device_plant.py
  app/schemas/measurement.py
  app/service/common/middleware.py
  app/service/measurements.py
  app/service/rabbitmq/consumer.py
  app/service/sql/init_table_measurements.sql
  docker-compose.yaml
  requirements.txt
Labels: WIP

#31 Tests unitarios - Capa de servicio
  .codecov.yml
  .github/workflows/tests.yaml
  .gitignore
  README.md
  app/main.py
  app/resources/rule_parser.py
  app/service/measurements.py
  app/tests/__init__.py
  app/tests/test_measurements.py
  requirements.txt
Labels: ready for review

#32 Hotfix en notificaciones
  app/resources/notification_checker.py
Labels: bug, ready for review
